# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
defaults: &defaults
  working_directory: ~/microservice/menu
  shell: /bin/bash --login
  docker:
    - image: circleci/php:7.1.19-fpm-stretch-node-browsers
    
version: 2
jobs:
  prepare:
    <<: *defaults

    steps:
      - checkout

      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      # Download and cache dependencies

      # composer cache
      - restore_cache:
          keys:
          # "composer.lock" can be used if it is committed to the repo
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # node cache

      - restore_cache:
          keys:
            - node-v3-{{ checksum "package.json" }}
            - node-v3-
      - run: yarn install
      - save_cache:
          key: node-v3-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.yarn

      # prepare the database
      - run: touch storage/testing.sqlite
      - run: php artisan migrate --env=testing --database=sqlite_testing --force
      
      # generate key
      - run: php artisan key:generate
      
      - persist_to_workspace:
          root: ~/microservice
          paths:
            - ui
  test:
    <<: *defaults
    steps:
    
      - attach_workspace:
          at: ~/microservice
      # run tests with phpunit or codecept
      - run: ./vendor/bin/phpunit
      
      - store_test_results:
          path: microservice/_output
      - store_artifacts:
          path: microservice/_output
          
workflows:
  version: 2
  build_and_test:
    jobs:
      - prepare
      - test:
          requires:
            - prepare
          filters:
            branches:
              only: master